services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgres/data
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_USERNAME=root
      - MONGO_INITDB_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - /data/db